import { create } from "zustand";

import { CreateProperty, Property, UpdateProperty } from "./domainSchemas";
import { testProperties } from "./testData";

interface DataResponse<T> {
    data: T;
    error?: undefined;
}
interface ErrorResponse {
    data?: undefined;
    error: Error
}
type StoreResponse<T = undefined> = DataResponse<T> | ErrorResponse

interface PropertyStore {
    properties: Property[],
    createProperty: (newPropertyData: CreateProperty) => Promise<StoreResponse<Property['id']>>,
    removeProperty: (propertyId: Property['id']) => Promise<StoreResponse>,
    updateProperty: (propertyId: Property['id'], updatedProperty: UpdateProperty) => Promise<StoreResponse>
}

export const usePropertyStore = create<PropertyStore>((set) => ({
    properties: testProperties,
    createProperty: async (newPropertyData) => {
        // this data is generated by the db
        const newId: string = new Date().getTime().toString();
        const newProperty: Property = {
            id: newId,
            ...newPropertyData
        }

        set((prevState) => ({ properties: [...prevState.properties, newProperty] }))
        return { data: newProperty.id };
    },
    removeProperty: async (propertyId) => {
        set((prevState) => ({ properties: prevState.properties.filter((property) => property.id != propertyId) }))

        return { data: undefined }
    },
    updateProperty: async (propertyId, updatedProperty) => {
        set((prevState) => ({ properties: prevState.properties.map((property) => property.id == propertyId ? { ...property, ...updatedProperty } : property) }))
    
        return { data: undefined }
    },
}))
