/** This file exposes stores that manages the data of the system
 * 
 * It has methods to perform CRUD operations & local copies of the info for quick access
 */
import { create } from "zustand";

import { CreatePersonSchema, CreatePropertySchema, PersonSchema, PropertySchema, UpdatePropertySchema } from "./domainSchemas";
import { testPersons, testProperties } from "./testData";


/** Describes the response returned by the operations on the store
 * 
 * Errors are not thrown, they are returned to be handled by consumer
 */
interface DataResponse<T> {
    data: T;
    error?: undefined;
}
interface ErrorResponse {
    data?: undefined;
    error: Error
}
type StoreResponse<T = undefined> = DataResponse<T> | ErrorResponse

/** Describes a store for properties
 */
interface PropertyStore {
    properties: PropertySchema[],
    createProperty: (newPropertyData: CreatePropertySchema) => Promise<StoreResponse<PropertySchema['id']>>,
    removeProperty: (propertyId: PropertySchema['id']) => Promise<StoreResponse>,
    updateProperty: (propertyId: PropertySchema['id'], updatedProperty: UpdatePropertySchema) => Promise<StoreResponse>
}

export const usePropertyStore = create<PropertyStore>((set) => ({
    properties: testProperties,
    createProperty: async (newPropertyData) => {
        // this data is generated by the db
        const newId: string = new Date().getTime().toString();
        const newProperty: PropertySchema = {
            id: newId,
            ...newPropertyData
        }

        set((prevState) => ({ properties: [...prevState.properties, newProperty] }))
        return { data: newProperty.id };
    },
    removeProperty: async (propertyId) => {
        set((prevState) => ({ properties: prevState.properties.filter((property) => property.id != propertyId) }))

        return { data: undefined }
    },
    updateProperty: async (propertyId, updatedProperty) => {
        set((prevState) => ({ properties: prevState.properties.map((property) => property.id == propertyId ? { ...property, ...updatedProperty } : property) }))
    
        return { data: undefined }
    },
}))

interface PersonStore {
    persons: PersonSchema[],
    createPerson: (newPersonData: CreatePersonSchema) => Promise<StoreResponse<PersonSchema['id']>>
}

export const usePersonStore = create<PersonStore>((set) => ({
    persons: testPersons,
    createPerson: async (newPersonData) => {
        //this data is generated by the db
        const newId: string = new Date().getTime().toString();
        const newPerson: PersonSchema = {
            id: newId,
            ...newPersonData
        }

        set((prevState) => ({ persons: [...prevState.persons, newPerson]}))
        return { data: newPerson.id }
    }
}))